### ISSUE TITLE
Permitir reportes a través de SMS

### ISSUE THREAD

**Issue by jreyes33** [desastre-ecuador/mapa.desastre.ec#10]
Durante la reunión, se propuso utilizar [gammu](http://wammu.eu/gammu/) para recibir alertas vía SMS y luego enviarlas como reportes al [API REST de Ushahidi](https://wiki.ushahidi.com/display/WIKI/Ushahidi+REST+API). El endpoint sería https://mapa.desastre.ec/?task=report.

**Comment by codeadict** [comment]
Estaba pensando en usar https://www.rapidsms.org/ pero Gammu esta bien mas simple, si nadie esta trabajando en esto puedo colaborar esta noche.

**Comment by jreyes33** [comment]
@codeadict esta tarea ya la están realizando @bluewake y @wikicarlos
