### ISSUE TITLE
Actionable Plugin

### ISSUE THREAD

**Issue by Nhorning** [desastre-ecuador/mapa.desastre.ec#101]
Quakemap.org made use of a heavily modified actionable plugin (by @himalayantechies, most suited to this workflow: 
https://docs.google.com/presentation/d/1C7KRFkumjeclHrPKqGAQujkjlFng4_Gk0Hy6S-BvHjo/edit?usp=sharing

More on Quakemap: https://sites.google.com/site/dhnnepalcoordinator/projects/quakemap

This may or may not be compatible with the mapa.desastre.ec workflow.  But this plugin is probably one the most transferable plugins we have ready to go: 
Repo: https://github.com/himalayantechies/Ushahidi_Web/tree/develop/plugins/actionable

**Comment by jreyes33** [comment]
Thanks for sharing, @Nhorning. This plugin was added yesterday. We even contributed back [this pull request](https://github.com/ushahidi/Ushahidi-plugin-actionable/pull/3).

Is there anything extra to be done, or are we ok closing this issue?

**Comment by Nhorning** [comment]
I can't remember if our changes got completely merged back into the original, but ours was better ;)  More specifically, we structured whether reports were closed or not in a more rational way.  Reports could be closed whether action was taken on them or not. They also could be filtered on the map by their actionable status rationally.

![1902_airlift_success01](https://cloud.githubusercontent.com/assets/1872181/14829038/4f6a9838-0c09-11e6-8926-9e5af2a3d597.png)

Live example link: http://www.quakemap.org/reports/view/932

I understand better than most people that time for one of these deployments is a highly limited resource, but if you can spare it, it might be worth checking if our version fits your workflow better.   Otherwise, of course it's OK if you close it.

**Comment by jreyes33** [comment]
It seems like I missed the "heavily modified" part :smile:. I'm trying to integrate it into our installation right now.

**Comment by jreyes33** [comment]
Thanks, @Nhorning, I managed to implement your version of the plugin (plus our modifications) in https://mapa.desastre.ec

**Comment by Nhorning** [comment]
Great!  I hope it works well for your deployment.
