### ISSUE TITLE
Monitoreo y alertas

### ISSUE THREAD

**Issue by bluewake** [desastre-ecuador/mapa.desastre.ec#106]
Se requiere generar una alerta en el caso de que el sitio deje de estar disponible. La alerta puede ser a través de correo electrónico y si es posible integrado a grupo Telegram.

**Comment by jreyes33** [comment]
Se está monitorizando la disponibilidad de ambos sitios con New Relic. En caso de fallo se envía una alerta por correo y al grupo de Telegram.

### Reportes
- [Nivel de servicio mapa.desastre.ec](http://synthetics.newrelic.com/report/7NaLR)
- [Nivel de servicio ayudaecuador.ec](http://synthetics.newrelic.com/report/JBvpO)
