### ISSUE TITLE
Crear formulario para voluntarios

### ISSUE THREAD

**Issue by jreyes33** [desastre-ecuador/mapa.desastre.ec#13]
Formulario para suscripción de voluntarios que quieran inscribirse en uno de los tres grupos

**Comment by crisguitar** [comment]
Esto aparece en el Trello como cerrado. ¿Podemos agregar el link del formulario aquí o en el Trello para poder revisar y cerrar el issue?

**Comment by jreyes33** [comment]
Volvió a Doing en trello https://trello.com/c/dUVAuzGo

**Comment by luisloaiza** [comment]
¿Qué tipo de voluntarios están registrando aquí?

**Comment by carlast22** [comment]
@luisloaiza ese formulario es solo para que se registren dentro de los grupos que estamos divididos: técnico, coordinación, enlace o verificación. Tenemos otro ticket para que se inscriban voluntarios in situ que ayuden creando reportes.
