### ISSUE TITLE
Usar la API de uhsahidi para reportar con más facilidad

### ISSUE THREAD

**Issue by crisguitar** [desastre-ecuador/mapa.desastre.ec#21]

**Comment by tuxpiper** [comment]
Algunos puntos sobre el uso de la API para crear reportes
- method: POST
- endpoint: direccion base del servidor + "/api"
- ~~autenticación: HTTP basic auth , con nombre de usuario y password tal como están creados en la herramienta~~
- tipo contenidos: x-www-form-urlencoded
- campos:

task = ''report"
incident_title
incident_description
incident_category -- lista de identificadores de categoria numericos
latitude
longitude
incident_date -- formato strftime("%m/%d/%Y")
incident_hour -- formato strftime("%I")
incident_minute -- formato strftime("%M")
incident_ampm -- formato strftime("%p")
location_name

**Comment by tuxpiper** [comment]
Ejemplo en Python (usando la libreria requests )

```
import requests

def add_report_to_platform(mapurl, **kwargs):
    """
    known property names:
      incident_title, incident_description, incident_category,
      latitude, longitude, incident_date, incident_hour, incident_minute, incident_ampm, location_name
    """
    if not kwargs.has_key('latitude'): kwargs['latitude'] = 0
    if not kwargs.has_key('longitude'): kwargs['longitude'] = 0
    if not kwargs.has_key('location_name'): kwargs['location_name'] = "unknown"

    payload = { 'task': 'report' }
    payload.update(kwargs)

    r = requests.post(mapurl+"api", data=payload);

    return(r)

add_report_to_platform("https://mapa.desastre.ec",
  incident_title="Test",
  incident_description="Descripcion",
  incident_category=[1, 3],
  latitude="42.1",
  longitude="-20.2",
  incident_date="12/31/2015",
  incident_hour="12",
  incident_minute="59",
  incident_ampm="AM",
  location_name="Calle, Ciudad, Provincia")
```

**Comment by tuxpiper** [comment]
Si hay custom forms que tratar, por desgracia la única forma de manejarlo sería añadiendo código específico para esos forms. El código que sería relevante está ubicado aquí:

https://github.com/desastre-ecuador/mapa.desastre.ec/blob/master/application/libraries/api/MY_Report_Api_Object.php#L51

**Comment by apardo** [comment]
En la mañana de Ecuador de hoy 20 de abril van a comenzar las pruebas del SMS. ¿Están en el equipo técnico? https://telegram.me/joinchat/AbmN-wcPvovTZcL0Lpr14Q

**Comment by tuxpiper** [comment]
Hola Antonio, sí yo estoy como @davidlosada

Saludos
