### ISSUE TITLE
[Template] Revisar pie de página

### ISSUE THREAD

**Issue by silenceway** [desastre-ecuador/mapa.desastre.ec#24]
Menú se sale de la pantalla en pantallas pequeñas.

**Comment by claucece** [comment]
Que sea responsivo.

**Comment by andreslucena** [comment]
Creo que ahora ya es responsivo: 

![seleccion_079](https://cloud.githubusercontent.com/assets/717367/14714429/340b73b4-07e5-11e6-89c7-cee69cfefd4c.png)

Cerramos la issue?
