### ISSUE TITLE
[Template] Mensaje de página inicial por debajo del menú

### ISSUE THREAD

**Issue by silenceway** [desastre-ecuador/mapa.desastre.ec#31]

**Comment by crisguitar** [comment]
Podemos cerrar este issue?

<img width="1149" alt="screen shot 2016-04-21 at 2 39 30 pm" src="https://cloud.githubusercontent.com/assets/2355302/14721977/e7b996c8-07ce-11e6-9643-38f91ef53dc1.png">

=)
