### ISSUE TITLE
Un clone --recursive del repo no descarga las locales

### ISSUE THREAD

**Issue by apardo** [desastre-ecuador/mapa.desastre.ec#4]

**Comment by andreslucena** [comment]
Creo que lo mejor es directamente descargar y subir los ficheros del submodule y quitarlo. Esto es util para el caso estandar de Ushahidi, en el que se quiere mantener y poder actualizar los ficheros de internacionalizacion del localeapp. 

En nuestro caso si queremos cambiar alguno tendríamos que hacer un fork del repo de I18N, configurar el localeapp, configurar todo apuntando a esto; siendo demasiado complejo. Creo que nos vale con tener los ficheros .YML quitando el submodule. @apardo como lo ves?

**Comment by apardo** [comment]
+1

**Comment by apardo** [comment]
Solucionado https://github.com/desastre-ecuador/mapa.desastre.ec/commit/bd0c6ed00a5691fa8d65797c136cdcd9683a1fc3
