### ISSUE TITLE
[Template] La página de reportes no muestra reportes en browser

### ISSUE THREAD

**Issue by crisguitar** [desastre-ecuador/mapa.desastre.ec#41]
Cuando la ventana está maximizada no se pueden ver los reportes. Solo se ven al hacer pequeña la pantalla.

**Comment by andreslucena** [comment]
Hola @crisguitar. Te referis a esta URL: https://mapa.desastre.ec/reports ?

**Comment by crisguitar** [comment]
Este: http://beta.mapa.desastre.ec/reports

**Comment by silenceway** [comment]
Fixed in https://github.com/desastre-ecuador/mapa.desastre.ec/pull/44/commits/ab3c984b1447c5f056c18bb591c9e2a6965e6970
