### ISSUE TITLE
Permitir embeber el mapa en otras webs

### ISSUE THREAD

**Issue by andreslucena** [desastre-ecuador/mapa.desastre.ec#43]
Tendría que ser a través de un iframe o similar. Sería para la home principal de https://desastre.ec, que actualmente usamos otro mapa en la portada. 

Estaba probando en local https://github.com/SkyTruth/ushahidi-embed y parece que funciona bastante bien: 

![seleccion_077](https://cloud.githubusercontent.com/assets/717367/14677900/f1f17ebe-0713-11e6-91c4-213f7c420898.png)

Habría que modificar la plantilla de desastre.ec para que tenga lo siguiente: 

```
<section id="mapa" class="mapa-section">
        <div class="container">
            <div class="col-lg-12">
                    <iframe src="http://localhost:8080/embed" height="680px" width="100%"></iframe>
            </div>
        <div>
    </div>
  </div>
</section>
```

Si les parece ya subo el plugin ese para que podamos hacer pruebas con producción o buscamos alguna otra solución más vistosa.

**Comment by silenceway** [comment]
Hay una versión funcionando en beta, con correcciones hechas al plugin sugerido.
