### ISSUE TITLE
Borrar el directorio installer al hacer deploy

### ISSUE THREAD

**Issue by apardo** [desastre-ecuador/mapa.desastre.ec#47]
Documentación de como hacerlo con Capistrano:
http://capistranorb.com/documentation/getting-started/before-after/

**Comment by apardo** [comment]
También reiniciar Apache

**Comment by andreslucena** [comment]
Ya estoy trabajando en ello en esta PR https://github.com/desastre-ecuador/mapa.desastre.ec/pull/67 

¿Para que hace falta reiniciar apache?
