### ISSUE TITLE
Revisar que tanto mapa como filtros de mapa sean responsivos

### ISSUE THREAD

**Issue by claucece** [desastre-ecuador/mapa.desastre.ec#50]
Tanto en móviles como en computadoras.

**Comment by andreslucena** [comment]
- [x] Escritorio - Ubuntu - Firefox: funciona bien 
- [x] Escritorio - Ubuntu - Chrome: funciona bien 
- [x] Móvil - Android - Firefox: funciona bien 
- [x] Móvil - Android - Chrome: funciona bien 
- [x] Tablet - Android - Chrome: funciona bien 
- [ ] Tablet - Android - Navegador por defecto: no se ve el mapa, adjunto pantallazo. No se si estará relacionado con el error del SSL de contenido mixto (HTTP y HTTPS). 

![screenshot_2016-04-21-13-26-08](https://cloud.githubusercontent.com/assets/717367/14707521/8021fd7e-07c5-11e6-9abe-f72d9f2b83e8.png)
