### ISSUE TITLE
[Template] Páginas "Recibir Alertas" y "Contacto" revisarlas para móvil

### ISSUE THREAD

**Issue by silenceway** [desastre-ecuador/mapa.desastre.ec#55]

**Comment by silenceway** [comment]
Fixed alerts in https://github.com/desastre-ecuador/mapa.desastre.ec/commit/966014efe699fa3adc9604b1ec43171f05c357d4

**Comment by andreslucena** [comment]
¿Se puede cerrar este ticket?
