### ISSUE TITLE
[Template] Ajusta mensaje de bienvenida

### ISSUE THREAD

**Issue by silenceway** [desastre-ecuador/mapa.desastre.ec#57]
Evitar que esté al 100% del navegador el mensaje de bienvenida.

**Comment by andreslucena** [comment]
¿Esto sigue pasando o con los cambios del diseño ya esta solucionado? 

Si me pasas un pantallazo de donde esta el error y con que resoluciones ocurre ya lo revisamos.

**Comment by crisguitar** [comment]
No entiendo muy bien este issue. Necesitamos redefinirlo? o cerrarlo?

**Comment by silenceway** [comment]
Ya está solucionado con la última versión
