### ISSUE TITLE
No se puede cambiar el radio de la alerta

### ISSUE THREAD

**Issue by apardo** [desastre-ecuador/mapa.desastre.ec#64]
No se puede cambiar el radio de la alerta en la subscripción a alertas:
https://mapa.desastre.ec/alerts

El mensaje de la consola Javascript es:
Uncaught TypeError: Cannot read property 'addClass' of undefined

**Comment by andreslucena** [comment]
En mi caso en la consola de Firefox veo esta traza de error: 

```
TypeError: g is undefined
._mouseCapture()
 jquery.ui.min.js:21
._mouseDown()
 jquery.ui.min.js:13
._mouseInit/<()
 jquery.ui.min.js:13
x.event.dispatch()
 jquery.js:5
x.event.add/v.handle()
 jquery.js:5
 jquery.ui.min.js:21:3709
```

**Comment by apardo** [comment]
Arreglado
