### ISSUE TITLE
Problemas con paginación en API pública

### ISSUE THREAD

**Issue by wikicarlos** [desastre-ecuador/mapa.desastre.ec#70]
Muchach@s
Estoy haciendo un manual del public api para interconectarnos, una revisada rápida a: https://wiki.ushahidi.com/display/WIKI/Ushahidi+Public+API

Basicamente envio parametros y recivo un json.
https://mapa.desastre.ec/api?task=incidents&by=sinceid&id=10
Pero el filtro más importante que sería desde que id mostrar no funciona, pareciera que lo ignora.
by=sinceid&id=100 devuelve lo mismo.

Creo que la función está en el archivo 
mapa.desastre.ec/application/libraries/api/MY_Incidents_Api_Object.php
en la función perform_task (LINE 52)

Gracias,

**Comment by jreyes33** [comment]
Logramos mostrar los incidentes de manera ascendente agregando algunos parámetros a la cadena de consulta:
https://mapa.desastre.ec/api?task=incidents&by=sinceid&id=0&sort=0&orderfield=incidentid
https://mapa.desastre.ec/api?task=incidents&by=sinceid&id=28&sort=0&orderfield=incidentid
etc...

Adicionalmente, este otro endpoint sería útil para la paginación:
https://mapa.desastre.ec/api?task=incidentcount

Saludos,

**Comment by jreyes33** [comment]
@wikicarlos Revisando [este comentario en otro issue](https://github.com/desastre-ecuador/mapa.desastre.ec/issues/3#issuecomment-212832781) me encontré con estas otras formas de consumir los reportes.

Por RSS:

https://mapa.desastre.ec/feed?p=1
https://mapa.desastre.ec/feed?p=2
...

Por AtomPub
https://mapa.desastre.ec/feed/atom?p=1
https://mapa.desastre.ec/feed/atom?p=2
...

¿Crees que con esto tengamos suficiente para poder cerrar este issue?

**Comment by wikicarlos** [comment]
GENIAL ! dalo por hecho =)
