### ISSUE TITLE
Mensaje en Ingles en la página posterior al envio de reporte.

### ISSUE THREAD

**Issue by wikicarlos** [desastre-ecuador/mapa.desastre.ec#75]
https://mapa.desastre.ec/reports/thanks

![image](https://cloud.githubusercontent.com/assets/9935374/14724443/d5c87c4c-07db-11e6-9378-f6dbb264d422.png)

**Comment by 00dav00** [comment]
Hola, cree un PR (https://github.com/desastre-ecuador/mapa.desastre.ec/pull/91) para este issue.

**Comment by 00dav00** [comment]
![screenshot from 2016-04-26 00 44 33](https://cloud.githubusercontent.com/assets/9206778/14808316/f6a603c8-0b49-11e6-97ef-cf42c6d45222.png)

**Comment by jreyes33** [comment]
Cerrado con el PR #91 de @00dav00
