### ISSUE TITLE
Añadir el campo "Submited by" al documento exportado

### ISSUE THREAD

**Issue by vechocho** [desastre-ecuador/mapa.desastre.ec#80]
Seria bueno que en el documento final exportado en cvs también apareciera el campo "submited by" ya que cuando se genera un reporte a partir de sms este campo se llena con el numero de teléfono del que reporta. Esto seria muy bueno al pasar los datos al ECU911 ya que ayuda a la verificación.
![snip_ushahidi](https://cloud.githubusercontent.com/assets/13081080/14765009/cac6ddfc-0993-11e6-8e6a-8baf4241c7a8.png)

**Comment by silenceway** [comment]
Actualizado en commit https://github.com/desastre-ecuador/mapa.desastre.ec/commit/731d8b43c5a776ad115d2812740bbba192003ebc
