### ISSUE TITLE
No se muestra el mapa para filtrar por ubicación en la página de reportes

### ISSUE THREAD

**Issue by jreyes33** [desastre-ecuador/mapa.desastre.ec#81]
En [esta página](https://mapa.desastre.ec/reports/) no se puede filtrar por ubicación porque no se despliega el mapa. Ver captura de pantalla:

![falta el mapa](https://cloud.githubusercontent.com/assets/117723/14765427/4013c216-09a6-11e6-9432-2d17a05324a0.png)

**Comment by silenceway** [comment]
Corregido en commit https://github.com/desastre-ecuador/mapa.desastre.ec/commit/453c780aa2557fc5260097f4cab21bad25ecf67e (desplegado en beta)
