### ISSUE TITLE
Sección de visualización de reportes no muestra la lista completa

### ISSUE THREAD

**Issue by fexadom** [desastre-ecuador/mapa.desastre.ec#89]

**Comment by fexadom** [comment]
Al querer visualizar los reportes en el mapa, la lista de reportes que aparece no se puede desplazar o hacer "scroll" y solo se puede ver el primer reporte.
![capture](https://cloud.githubusercontent.com/assets/9542322/14795375/d6f5419e-0aed-11e6-9cd6-4b29570b521d.PNG)

**Comment by jreyes33** [comment]
Gracias por reportarlo. Este defecto fue introducido al embeber el mapa en la página principal. Ver desastre-ecuador/AyudaEcuador#16
