### ISSUE TITLE
El mapa embebible se comporta inesperadamente

### ISSUE THREAD

**Issue by crisguitar** [desastre-ecuador/mapa.desastre.ec#90]
Cuando se hace click en uno de los reportes que se muestran en el mapa en [desastre.ec](http://desastre.ec/#mapa) el interior del div es actualizado por la pagina de mapa.desastre.ec.

![screen shot 2016-04-25 at 9 38 18 pm](https://cloud.githubusercontent.com/assets/2355302/14805107/ad62d616-0b2e-11e6-92ee-7f53147f5b9a.png)

**Comment by jreyes33** [comment]
Gracias por reportarlo. Me parece que es duplicado del #89, por eso lo cierro.
